package gRPC

import java.util.concurrent.TimeUnit
import java.util.logging.{Level, Logger}

import com.logfile.proto.logfile.{GreeterGrpc, logRequest}
import com.logfile.proto.logfile.GreeterGrpc.GreeterBlockingStub
import io.grpc.{StatusRuntimeException, ManagedChannelBuilder, ManagedChannel}
import com.typesafe.config.ConfigFactory

/*
gRPC implementation referenced from the below repo:
https://github.com/xuwei-k/grpc-scala-sample/tree/master/grpc-scala/src/main/scala/io/grpc/examples/helloworld
*/

object gRPCClient {

  // Configuring the local port
  val port = ConfigFactory.load().getInt("port")

  def apply(host: String, port: Int): gRPCClient = {

    // Linking the stubs generated by the protobuffs
    val channel = ManagedChannelBuilder.forAddress(host, port).usePlaintext().build
    val blockingStub = GreeterGrpc.blockingStub(channel)
    new gRPCClient(channel, blockingStub)
  }

  // Instantiating the gRPC client with the input parameters of time and differential time
  def main(args: Array[String]): Unit = {
    val client = gRPCClient("localhost", port)
    try {
      val output = args.headOption.getOrElse("19:24:15,03:00:00")
      client.response(output)
    } finally {
      client.shutdown()
    }
  }
}

class gRPCClient private( private val channel: ManagedChannel, private val blockingStub: GreeterBlockingStub ) {

  private[this] val logger = Logger.getLogger(classOf[gRPCClient].getName)

  def shutdown(): Unit = {
    channel.shutdown.awaitTermination(5, TimeUnit.SECONDS)
  }

  // Defining the response header for the GET response
  def response(name: String): Unit = {
    val request = logRequest(name)
    try {
      val response = blockingStub.sayHello(request)
      logger.info("Greeting: " + response.message)
      response.message
    }
    catch {
      case e: StatusRuntimeException =>
        logger.log(Level.WARNING, "RPC failed: {0}", e.getStatus)
    }
  }
}
